slogan: Far the most important thing is to settle accounts with myself.

menu:
  - title: Home
    url: 
    intro: Shigaro's Home
    icon: "fa fa-bank"
  - title: Archives
    url: archives
    intro: "All the articles."
    icon: "fa fa-archive"
  - title: Categories
    url: categories
    intro: "All the categories."
    icon: "fa fa-folder"
  - title: Tags
    url: tags
    intro: "All the tags."
    icon: "fa fa-tags"
  - title: About
    url: about
    intro: "About me."
    icon: "fa fa-user"

links:
  - title: "Github-minyez"
    url: https://github.com/minyez
    intro: "My Github account."
    icon: "fa fa-github-square"
    # - title: "Weibo-PytLab"
    # - url: http://weibo.com/shaowugui 
    # - intro: "My Weibo account."
    # - icon: "fa fa-weibo"
    # - title: "Zhihu-Minye Zhang"
    # - intro: "My Zhihu"
    # - url: https://www.zhihu.com/people/Minye-Zhang
    # - icon: "fa fa-link"
    #  - title: "StackOverflow-PytLab"
    # url: http://stackoverflow.com/users/4014840/pytlab
    # intro: "My StackOverflow account"
    # icon: "fa fa-stack-overflow"
  - title: "DouBan-Shigaro"
    url: https://www.douban.com/people/shigaro/
    intro: "My DouBan account"
    icon: "fa fa-book" 
  - title: "Email"
    url: mailto:zmysmile0929@163.com
    intro: "Send Email to me"
    icon: "fa fa-mail-forward"
  - title: "Site source"
    url: https://github.com/minyez/minyez.github.io/tree/hexo
    intro: "Source codes of this site"
    icon: "fa fa-code"
    #  - title: "Hexo Repo"
    #    url: https://github.com/hexojs/hexo
    #    icon: "fa fa-code-fork"
    #  - title: "Original Freemind Repo"
    #    url: https://github.com/wzpan/hexo-theme-freemind
    #    icon: "fa fa-code-fork"
  

widgets:
- search
#- recent_posts  
- category
- tagcloud
- links

rss: true
fancybox: true
#favicon: img/douban_16x16.png #favicon.jpg
#favicon: /images/favicon/favicon.ico
favicon: true
# will use source/images/favicon/icon.png
background:

# Analytics
google_analytics:
  enable: true
  siteid: UA-111612868-1
baidu_tongji:
  enable: false
  siteid: shigaro.org
busuanzi:
# number of page views from busuanzi
  pageview: false
# number of total visitors from busuanzi
  visitor: true
# use hexo-wordcount to count total words
wordcount:
  site: true
  post: true

# search
# swiftype_key: ZP2ZSuHgipSZfRyU8uTR

# share widgets
bdshare: false
jiathis: false
